version: '2'

services:
  fusekiconfig:
    image: openuniversity/fuseki-iserve-config

  fusekidata:
    image: busybox
    volumes:
      - fuseki:/fuseki/databases

  redisdata:
    image: busybox
    volumes:
      - redis:/data

  rdfstore:
    image: stain/jena-fuseki
    volumes_from:
      - fusekiconfig
      - fusekidata
    ports:
      - "3030:3030"
    networks:
      - back-tier
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_BASE=/fuseki
      - JVM_ARGS=-Xms1500m -Xmx2500m
    command: /jena-fuseki/fuseki-server --set tdb:fileMode=direct

  redis:
      image: redis
      volumes_from:
        - redisdata
      ports:
        - "6379:6379"
      networks:
        - back-tier
      command: redis-server
  
  iservedata:
    image: busybox
    volumes:
      - iserve:/iserve  
    
  iserve:
    image: openuniversity/iserve
    ports:
      - "8080:8080"
    links:
      - rdfstore
      - redis
    volumes_from:
      - iservedata
    networks:
      - front-tier
      - back-tier
    environment:
      - LOG_LEVEL=info
      - ISERVE_HOST=192.168.99.100
      - ISERVE_PORT=8080
      - ISERVE_BASE=/opt/iserve
      - ISERVE_DATA=/iserve
      - ISERVE_REPOSITORY=iserve
      - RDFSTORE_HOST=rdfstore
      - RDFSTORE_PORT=3030
      - RDFSTORE_TYPE=fuseki
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JVM_ARGS=-Xms800m -Xmx1500m
    command: /opt/iserve/scripts/setup-and-run.sh

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

volumes:
  redis:
    {}
  fuseki:
    {}
  iserve:
    {}
