version: '2'

services:
  iservedata:
    image: busybox
    volumes:
      - iserve-data:/iserve  
  iserve:
    image: openuniversity/iserve
    ports:
      - "8080:8080"
    volumes_from:
      - iservedata
    environment:
      - LOG_LEVEL=info
      - ISERVE_HOST=192.168.99.100
      - ISERVE_PORT=8080
      - ISERVE_BASE=/opt/iserve
      - ISERVE_DATA=/iserve
      - ISERVE_REPOSITORY=iserve
      - RDFSTORE_HOST=192.168.99.100
      - RDFSTORE_PORT=3030
      - RDFSTORE_TYPE=fuseki
      - JVM_ARGS=-Xms800m -Xmx1500m
    command: /opt/iserve/scripts/setup-and-run.sh

volumes:
  iserve-data:
    {}
