iservedata:
  image: busybox
  volumes:
    - /Users/cp3982/Workspace/Data/docker-runtime/iserve:/iserve  
iserve:
  image: openuniversity/iserve
  ports:
    - "8080:8080"
  links:
    - rdfstore:rdfstore
    - redis:redis
  volumes_from:
    - iservedata
  environment:
    - LOG_LEVEL=info
    - ISERVE_HOST=192.168.99.108
    - ISERVE_PORT=8080
    - ISERVE_BASE=/opt/iserve
    - ISERVE_DATA=/iserve
    - ISERVE_REPOSITORY=iserve
    - RDFSTORE_HOST=rdfstore
    - RDFSTORE_PORT=3030
    - RDFSTORE_TYPE=fuseki
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - JVM_ARGS=-Xms800m -Xmx1500m
  command: /opt/iserve/scripts/setup-and-run.sh
