fusekiconfig:
  image: openuniversity/fuseki-iserve-config

fusekidata:
  image: busybox
  volumes:
    - /Users/cp3982/Workspace/Data/docker-runtime/fuseki/databases:/fuseki/databases
    - /Users/cp3982/Workspace/Data/docker-runtime/fuseki/logs:/fuseki/logs

redisdata:
  image: busybox
  volumes:
    - /Users/cp3982/Workspace/Data/docker-runtime/redis:/data

rdfstore:
  image: stain/jena-fuseki
  volumes_from:
    - fusekiconfig
    - fusekidata
  ports:
    - "3030:3030"
  environment:
    - ADMIN_PASSWORD=admin
    - FUSEKI_BASE=/fuseki
    - JVM_ARGS=-Xms1500m -Xmx2500m
  command: /jena-fuseki/fuseki-server --set tdb:fileMode=direct

redis:
    image: redis
    volumes_from:
      - redisdata
    ports:
      - "6379:6379"
    command: redis-server