iservedata:
  image: busybox
  volumes:
    - /Users/cp3982/Workspace/Data/docker-runtime/iserve:/iserve
rdfstore:
  image: stain/jena-fuseki
#  image: openuniversity/fuseki
  volumes:
    - ./scripts:/fuseki/scripts
  ports:
    - "3030:3030"
  environment:
    - FUSEKI_BASE=/fuseki
    - JVM_ARGS=-Xmx2g
  entrypoint: /fuseki/scripts/setup-fuseki.sh
  command: /jena-fuseki/fuseki-server --set tdb:fileMode=direct
iserve:
#  image: openuniversity/iserve
  build: .
  ports:
    - "8080:8080"
  links:
    - rdfstore:rdfstore
  volumes_from:
    - iservedata
  environment:
    - ISERVE_HOST=192.168.99.100
    - ISERVE_PORT=8080
    - ISERVE_BASE=/opt/iserve
    - ISERVE_DATA=/iserve
    - ISERVE_REPOSITORY=iserve
    - RDFSTORE_HOST=rdfstore
    - RDFSTORE_PORT=3030
    - RDFSTORE_TYPE=fuseki
    - JVM_ARGS=-Xmx2g
  command: /opt/iserve/scripts/setup-and-run.sh
