version: '2'

services:
  fusekiconfig:
    image: openuniversity/fuseki-config-iserve

  fusekidata:
    image: busybox
    volumes:
      - fuseki-data:/fuseki/databases

  rdfstore:
    image: stain/jena-fuseki
    volumes_from:
      - fusekiconfig
      - fusekidata
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin
      - FUSEKI_BASE=/fuseki
      - JVM_ARGS=-Xms1500m -Xmx2500m
    command: /jena-fuseki/fuseki-server --set tdb:fileMode=direct
  
volumes:
  fuseki-data:
    {}