fusekidata:
  image: busybox
  volumes:
    - /Users/cp3982/Workspace/Data/docker-runtime/fuseki:/fuseki
redisdata:
  image: busybox
  volumes:
    - /Users/cp3982/Workspace/Data/docker-runtime/redis:/data
rdfstore:
  image: stain/jena-fuseki
  volumes:
    - ./scripts:/jena-fuseki/scripts
  volumes_from:
    - fusekidata
  ports:
    - "3030:3030"
  environment:
    - ADMIN_PASSWORD=admin
    - FUSEKI_BASE=/fuseki
    - JVM_ARGS=-Xms1500m -Xmx2500m
  entrypoint: /jena-fuseki/scripts/setup-fuseki.sh
  command: /jena-fuseki/fuseki-server --set tdb:fileMode=direct
redis:
    image: redis
    volumes_from:
      - redisdata
    ports:
      - "6379:6379"
    command: redis-server
    # command: redis-server --appendonly yes